# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def spider(comp_name):
  profile = webdriver.FirefoxProfile()
  # 1 - Allow all images
  # 2 - Block all images
  # 3 - Block 3rd party images 
  profile.set_preference("permissions.default.image", 2)
  options = Options()
  options.add_argument('-headless')

  driver = webdriver.Firefox(firefox_profile=profile)
  
  driver.get("https://www.google.com/search?client=firefox-b-d&q="+"site:glassdoor.co.in/overview "+comp_name)
  driver.set_window_size(890, 751)
  driver.find_element(By.XPATH, "//h3").click()
  cat = driver.find_element(By.XPATH, "//div/div[6]/span").text
  driver.quit()
  return cat